# Base URL for the website
baseURL = 'http://blog.louisfradin.com/'

# Website title
title = 'Louis FRADIN'

# This is what goes in <html lang="">
languageCode = 'en-us'

# Theme used
theme = "hugo-blog-awesome"

# This defines how dates are formatted
defaultContentLanguage = "en-gb"

# To enable Google Analytics 4 (gtag.js) provide G-MEASUREMENT_ID below.
# To disable Google Analytics, simply leave the field empty or remove the next line
googleAnalytics = '' # G-MEASUREMENT_ID

# Enable emojis globally
enableEmoji = true

# To enable Disqus comments, provide Disqus Shortname below.
# To disable Disqus comments, simply leave the field empty or remove the next line
disqusShortname = ''

# set markup.highlight.noClasses=false to enable code highlight
[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark.renderer]
    unsafe = true

[menu]
  [[menu.main]]
    pageRef="/"
    name = 'Home'
    url = '/'
    weight = 10
  [[menu.main]]
    pageRef="posts"
    name = 'Posts'
    url = '/posts/'
    weight = 20
  [[menu.main]]
    pageRef="about"
    name = 'About'
    url = '/about/'
    weight = 30

[params]
  sitename = "Louis FRADIN"
  defaultColor = "auto" # color mode: dark, light, auto
  description = "A Back-End / DevOps / SysAdmin Developer blog"
  mainSections = ['posts']
  toc = true # set to false to disable table of contents 'globally'
  goToTop = true # set to false to disable 'go to top' button

[params.author]
  avatar = "avatar.jpg" # put the file in assets folder; also ensure that image has same height and width
  # Note: image is not rendered if the resource(avatar image) is not found. No error is displayed.
  intro = "Louis FRADIN"
  name = "Louis FRADIN"
  description = "A Back-End / DevOps / SysAdmin Developer blog"

# Allow to override webmanifest options
[params.webmanifest]
  # name = "sitename" # will use "params.sitename" or "title" by default
  # short_name = "sitename" # same as name
  # start_url = "/" # will use homepage url by default
  # theme_color = "#434648" # default is "#434648" (base color of text). Also will override html `<meta name="theme-color" />`
  # background_color = "#fff" # by default depend on "params.defaultColor" for "light" or "auto" will be set to "#fff" for dark will be "#131418" (color of dark mode background)
  # display = "standalone"

# Allow to override `browserconfig.xml` params (configuration for windows embeded browsers)
[params.browserconfig]
  TileColor = "#2d89ef" # default windows 10 blue tile color

[[params.socialIcons]]
name = "github"
url = "https://github.com/lerenn"

# [[params.socialIcons]]
# name = "twitter"
# url = "https://twitter.com"

[[params.socialIcons]]
name = "Rss"
url = "index.xml"

[tableOfContents]
startLevel = 2 # ToC starts from H2
endLevel = 4 # ToC ends at H4
ordered = false # generates <ul> instead of <ol>
